get/urls.py
from django.urls import path
from . import views

app_name ='get'
urlpatterns = [
    path('', views.get_statistic,name='get_statistic'),
    path('login/', views.login_view,name='login_view'),
    path('menu_panel/',views.menu_panel,name='menu_panel'),
    path('post_new_meal/',views.post_new_meal,name='post_new_meal'),
    path('delete_meal/<slug:slug>',views.delete_meal,name='delete_meal'),
    path('modify_meal/<slug:slug>',views.modify_meal,name='modify_meal'),
    path('send_email/',views.send_email,name='send_email'),
    path('blog_panel/',views.blog_panel,name='blog_panel'),
    path('post_new_blog/',views.post_new_blog,name='post_new_blog'),
    path('delete_blog/<int:id>',views.delete_blog,name='delete_blog'),
    path('modify_blog/<int:id>',views.modify_blog,name='modify_blog'),
    path('show_email/',views.show_email,name='show_email'),
]

newtropical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
    path('subscribe/',include('subscribe.urls',namespace='subscribe')),
    path('about-us/',include('aboutus.urls',namespace='aboutus')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('',include('home.urls',namespace='home')),
    path('get/',include('get.urls',namespace='get')),
]
+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT))

subscribe/urls.py
from django.urls import path
from . import views

app_name ='subscribe'
urlpatterns = [
    path('sub/', views.subscribefunction,name='subscribe'),
]

get/models.py
from django.db import models

# Create your models here.

get/forms.py
from django import forms
from meals.models import Meals
from blog.models import Post

class MealsTableForm(forms.ModelForm):
    class Meta:
        model = Meals
        fields = ['name', 'description', 'image', 'price', 'category']

        image = forms.ImageField(required=False)

class PostTableForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','image','tags','category']

        image = forms.ImageField(required=False)

get/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from subscribe.models import subscribe
from meals.models import Meals
from meals.models import Category
from blog.models import Post
from .forms import MealsTableForm
from .forms import PostTableForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
import csv


# Create your views here.
@login_required(login_url='get:login_view')
def get_statistic(request):
    content = 'this is what I  wanna send'
    context = {'email_body':content}
    if request.method == 'POST':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="subscribes.csv"'

        writer = csv.writer(response)

        writer.writerow(['Name', 'Email'])

        all_subscribes = subscribe.objects.all()

        for sub in all_subscribes:
            writer.writerow([sub.name, sub.email])

        return response

    return render(request,'get/get_statistic.html',context)

@login_required(login_url='get:login_view')
def menu_panel(request):
    meals = Meals.objects.all()
    categories = Category.objects.all()
    context = {
        'meals':meals,
        'categories':categories
    }
    return render(request,'get/menu_control.html',context)

@login_required(login_url='get:login_view')
def post_new_meal(request):
    if request.method == 'POST':
        form = MealsTableForm(request.POST,request.FILES or None)
        print("FILES:", request.FILES)
        if form.is_valid():
            # 使用 update_or_create 来创建或更新对象
            if request.FILES:
                meal, created = Meals.objects.update_or_create(
                    name=form.cleaned_data['name'],
                    defaults={
                        'description': form.cleaned_data['description'],
                        'price': form.cleaned_data['price'],
                        'image': form.cleaned_data['image'] ,
                        'category': form.cleaned_data['category']
                    }
                )
            else:
                meal, created = Meals.objects.update_or_create(
                    name=form.cleaned_data['name'],
                    defaults={
                        'description': form.cleaned_data['description'],
                        'price': form.cleaned_data['price'],

                        'category': form.cleaned_data['category']
                    }
                )
            return redirect('get:menu_panel')

        else:
            # 如果表单无效，可以返回错误信息
            return render(request, 'get/post_new_meal.html', {'form': form})
    else:
        form = MealsTableForm()
        context = {'form': form}
        return render(request,'get/post_new_meal.html',context)

@login_required(login_url='get:login_view')
def delete_meal(request,slug):
    meal = get_object_or_404(Meals, slug=slug)
    meal.delete()
    return redirect('get:menu_panel')

@login_required(login_url='get:login_view')
def modify_meal(request,slug):
    meal = get_object_or_404(Meals,slug=slug)
    form = MealsTableForm(instance=meal)
    context = {'form':form}
    return render(request,'get/post_new_meal.html',context)

@login_required(login_url='get:login_view')
def send_email(request):
    context={}
    if request.method == 'POST':
        title = request.POST.get('subject')
        content = request.POST.get('message')
        all_subscribes = subscribe.objects.all()
        all_email = [subscriber.email for subscriber in all_subscribes]
        context={
            'title':title,
            'content':content,
            'email':all_email
        }
        return render(request, 'get/send_email.html', context)
    return render(request,'get/send_email.html',context)

@login_required(login_url='get:login_view')
def blog_panel(request):
    posts = Post.objects.all()
    context = {
        'posts':posts
    }
    return render(request, 'get/blog_control.html', context)

@login_required(login_url='get:login_view')
def post_new_blog(request):

    if request.method == 'POST':
        form = PostTableForm(request.POST,request.FILES or None)
        print("FILES:", request.FILES)
        if form.is_valid():
            # 使用 update_or_create 来创建或更新对象
            if request.FILES:
                author = User.objects.get(username='tony')
                post, created = Post.objects.update_or_create(
                    title=form.cleaned_data['title'],
                    defaults={
                        'author':author,
                        'content': form.cleaned_data['content'],
                        'tags': form.cleaned_data['tags'],
                        'image': form.cleaned_data['image'] ,
                        'category': form.cleaned_data['category']
                    }
                )
            else:
                author = User.objects.get(username='tony')
                post, created = Post.objects.update_or_create(
                    title=form.cleaned_data['title'],
                    defaults={
                        'author':author,
                        'content': form.cleaned_data['content'],
                        'tags': form.cleaned_data['tags'],

                        'category': form.cleaned_data['category']
                    }
                )
            return redirect('get:blog_panel')

        else:
            # 如果表单无效，可以返回错误信息
            return render(request, 'get/post_new_blog.html', {'form': form})
    else:
        form = PostTableForm()
        context = {'form': form}
        return render(request,'get/post_new_blog.html',context)

@login_required(login_url='get:login_view')
def delete_blog(request,id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect('get:blog_panel')

@login_required(login_url='get:login_view')
def modify_blog(request,id):
    post = get_object_or_404(Post,id=id)
    form = PostTableForm(instance=post)
    context = {'form':form}
    return render(request,'get/post_new_blog.html',context)

@login_required(login_url='get:login_view')
def show_email(request):
    all_subscribes = subscribe.objects.all()
    context = {'all_subscribes':all_subscribes}
    return render(request,'get/show_email.html',context)

def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('name')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('get:get_statistic')
        else:
            context = {
                'name':username,
                'password':password
            }
            return render(request,'get/login.html',context)

    return render(request,'get/login.html',context)

get/templates/get/blog_control.html
{% extends 'base.html' %}
{% load static %}
      {% block body %}
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Subscribe to us and you will get benefits from us from time to time!</h2>
                    <a href="{% url 'subscribe:subscribe' %}"><p class="lead">Click me to subscribe</p></a>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

      <div style="padding-left: 30px;">
          <a href="{% url 'get:post_new_blog' %}"><button class="btn-primary" style="align-items: center;">ADD </button></a>
        {% for post in posts %}


            <h5><a href="{% url 'get:modify_blog' post.id %}"><button class="btn-dark">Modify </button></a><a href="{% url 'get:delete_blog' post.id %}"><button class="btn-danger">Delete </button></a>{{ post }}</h5>

        {% endfor %}
      </div>

      </div> <!-- .main-wrap -->
    {% endblock %}

get/templates/get/get_statistic.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


      
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Press button get customer information(csv file)</h2>
                  <p class="lead">Follow us for a better dining experience.</p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->
        
        <div class="section" data-aos="fade-up">
          <div class="container">
            <div class="row justify-content-center mb-5">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Press button get customer information(csv file)</h2>
                <p class="lead">Subscribe to us and receive promotional and special information from time to time!</p>
              </div>
            </div>
            <div class="row justify-content-center">
              <div class="col-md-10 p-5 form-wrap">
                  {% if message %}
                      <h2>{{ message }}</h2>
                      <br>
                  {% endif %}
                {% comment %}
                <form action="#">
                  <div class="row mb-4">
                    <div class="form-group col-md-4">
                      <label for="name" class="label">Name</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-person"></span>
                        <input type="text" class="form-control" id="name">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="email" class="label">Email</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-email"></span>
                        <input type="email" class="form-control" id="email">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="phone" class="label">Phone</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-call"></span>
                        <input type="text" class="form-control" id="phone">
                      </div>
                    </div>

                    <div class="form-group col-md-4">
                      <label for="persons" class="label">Number of Persons</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-arrow-dropdown"></span>
                        <select name="persons" id="persons" class="form-control">
                          <option value="">1 person</option>
                          <option value="">2 persons</option>
                          <option value="">3 persons</option>
                          <option value="">4 persons</option>
                          <option value="">5+ persons</option>
                        </select>
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="date" class="label">Date</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-calendar"></span>
                        <input type="text" class="form-control" id="date">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="time" class="label">Time</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-time"></span>
                        <input type="text" class="form-control" id="time">
                      </div>
                    </div>
                  </div>
                  <div class="row justify-content-center">
                    <div class="col-md-4">
                      <input type="submit" class="btn btn-primary btn-outline-primary btn-block" value="Submit">
                      <!-- <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p> -->
                    </div>
                  </div>
                </form>
                {% endcomment %}
                  <form action="" method="post" style="padding-bottom: 50px;">
                      {% csrf_token %}


                      <button type="submit" class="btn btn-primary">GET TABLE</button>
                  </form>
                  <a href="{% url 'get:menu_panel' %}"><button class="btn btn-primary">Menu</button></a>
                  <a href="{% url 'get:blog_panel' %}"><button class="btn btn-primary">Blog</button></a>
                  <a href="{% url 'get:send_email' %}"><button class="btn btn-primary">Email</button></a>
                  <a href="{% url 'get:show_email' %}"><button class="btn btn-primary">Send</button></a>

              </div>
            </div>
          </div>
        </div> <!-- .section -->




  

      </div> <!-- .main-wrap -->

{% endblock %}
      

get/templates/get/login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


      
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Login(only for staff)</h2>
                  <p class="lead"></p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->
        
        <div class="section" data-aos="fade-up">
          <div class="container">
            <div class="row justify-content-center mb-5">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Login(only for staff)</h2>
                <p class="lead">Subscribe to us and receive promotional and special information from time to time!</p>
              </div>
            </div>
            <div class="row justify-content-center">
              <div class="col-md-10 p-5 form-wrap">
                  {% if message %}
                      <h2>{{ message }}</h2>
                      <br>
                  {% endif %}
                {% comment %}
                <form action="#">
                  <div class="row mb-4">
                    <div class="form-group col-md-4">
                      <label for="name" class="label">Name</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-person"></span>
                        <input type="text" class="form-control" id="name">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="email" class="label">Email</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-email"></span>
                        <input type="email" class="form-control" id="email">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="phone" class="label">Phone</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-call"></span>
                        <input type="text" class="form-control" id="phone">
                      </div>
                    </div>

                    <div class="form-group col-md-4">
                      <label for="persons" class="label">Number of Persons</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-arrow-dropdown"></span>
                        <select name="persons" id="persons" class="form-control">
                          <option value="">1 person</option>
                          <option value="">2 persons</option>
                          <option value="">3 persons</option>
                          <option value="">4 persons</option>
                          <option value="">5+ persons</option>
                        </select>
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="date" class="label">Date</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-calendar"></span>
                        <input type="text" class="form-control" id="date">
                      </div>
                    </div>
                    <div class="form-group col-md-4">
                      <label for="time" class="label">Time</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-time"></span>
                        <input type="text" class="form-control" id="time">
                      </div>
                    </div>
                  </div>
                  <div class="row justify-content-center">
                    <div class="col-md-4">
                      <input type="submit" class="btn btn-primary btn-outline-primary btn-block" value="Submit">
                      <!-- <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p> -->
                    </div>
                  </div>
                </form>
                {% endcomment %}
                  <form action="" method="post">
                      {% csrf_token %}

                      <div class="form-group col-md-4">
                      <label for="name" class="label">Name</label>
                      <div class="form-field-icon-wrap">
                        <span class="icon ion-android-person"></span>
                        <input type="text" class="form-control" id="name" name="name" value="{{ name }}">
                      </div>
                    </div>

                      <div class="form-group col-md-4">
                      <label for="password" class="label">Password</label>
                      <div class="form-field-icon-wrap">

                        <input type="password" class="form-control" id="password" name="password" value="{{ password }}">
                      </div>
                    </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                  </form>

              </div>
            </div>
          </div>
        </div> <!-- .section -->




  

      </div> <!-- .main-wrap -->

{% endblock %}
      

get/templates/get/menu_control.html
{% extends 'base.html' %}
{% load static %}
      {% block body %}
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Subscribe to us and you will get benefits from us from time to time!</h2>
                    <a href="{% url 'subscribe:subscribe' %}"><p class="lead">Click me to subscribe</p></a>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

      <div style="padding-left: 30px;">
          <a href="{% url 'get:post_new_meal' %}"><button class="btn-primary" style="align-items: center;">ADD </button></a>
        {% for category in categories %}
            <h4>{{ category }}</h4>
            <div>
            {% for meal in meals %}
                {% if meal.category == category %}
                    <h5><a href="{% url 'get:modify_meal' meal.slug %}"><button class="btn-dark">Modify </button></a><a href="{% url 'get:delete_meal' meal.slug %}"><button class="btn-danger">Delete </button></a>{{ meal }}</h5>
                {% endif %}
            {% endfor %}
            </div>
        {% endfor %}
      </div>

      </div> <!-- .main-wrap -->
    {% endblock %}

get/templates/get/post_new_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post new blog</title>
</head>
<body>
<form method="post" action="{% url 'get:post_new_blog' %}" enctype="multipart/form-data">
    {% csrf_token %}
{{ form }}
    <button type="submit">submit</button>
</form>
</body>
</html>

get/templates/get/post_new_meal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post new meal</title>
</head>
<body>
<form method="post" action="{% url 'get:post_new_meal' %}" enctype="multipart/form-data">
    {% csrf_token %}
{{ form }}
    <button type="submit">submit</button>
</form>
</body>
</html>

get/templates/get/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form id="mail_form" method="post">
    {% csrf_token %}
    title:<input type="text" id="subject" name="subject" value="{{ title }}"><br>
        content:<textarea id="message" name="message">{{ content }}</textarea><br>
        <button type="submit">Submit</button>
</form>
{% if title %}
<a href="mailto:{{ email|join:',' }}?subject={{ title }}&body={{ content|urlencode }}">Send</a>
{% endif %}
</body>
</html>

get/templates/get/show_email.html
{% extends 'base.html' %}
{% load static %}
      {% block body %}
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Subscribe to us and you will get benefits from us from time to time!</h2>
                    <a href="{% url 'subscribe:subscribe' %}"><p class="lead">Click me to subscribe</p></a>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

      <div style="padding-left: 30px;">

        <table class="table">
          <thead>
            <tr class="table-light">
              <th>Name</th>
              <th>Email</th>
              <th>Send</th>
            </tr>
          </thead>
          <tbody>
            {% for user in all_subscribes %}
            <tr class="tab-content">
              <td>{{ user.name }}</td>
              <td>{{ user.email }}</td>
              <td><a href="mailto:{{ user.email }}">Send</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      </div> <!-- .main-wrap -->
    {% endblock %}