blog/urls.py
from django.urls import path
from . import views

app_name ='blog'
urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('<int:id>', views.post_detail,name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag,name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category,name='post_by_category'),
    path('post_new/',views.post_new,name='post_new'),
]

get/urls.py
from django.urls import path
from . import views

app_name ='get'
urlpatterns = [
    path('', views.get_statistic,name='get_statistic'),
    path('login/', views.login_view,name='login_view'),
    path('menu_panel/',views.menu_panel,name='menu_panel'),
    path('post_new_meal/',views.post_new_meal,name='post_new_meal'),
    path('delete_meal/<slug:slug>',views.delete_meal,name='delete_meal'),
    path('modify_meal/<slug:slug>',views.modify_meal,name='modify_meal'),
    path('send_email/',views.send_email,name='send_email'),
    path('blog_panel/',views.blog_panel,name='blog_panel'),
    path('post_new_blog/',views.post_new_blog,name='post_new_blog'),
    path('delete_blog/<int:id>',views.delete_blog,name='delete_blog'),
    path('modify_blog/<int:id>',views.modify_blog,name='modify_blog'),
    path('show_email/',views.show_email,name='show_email'),
]

home/urls.py
from django.urls import path
from . import views

app_name ='home'
urlpatterns = [
    path('', views.home,name='home'),

]

meals/urls.py
from django.urls import path
from . import views

app_name ='meals'
urlpatterns = [
    path('', views.meal_list,name='meal_list'),
    path('<slug:slug>',views.meal_detail,name='meal_detail')
]

newtropical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
    path('subscribe/',include('subscribe.urls',namespace='subscribe')),
    path('about-us/',include('aboutus.urls',namespace='aboutus')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('',include('home.urls',namespace='home')),
    path('get/',include('get.urls',namespace='get')),
]
+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT))

subscribe/urls.py
from django.urls import path
from . import views

app_name ='subscribe'
urlpatterns = [
    path('sub/', views.subscribefunction,name='subscribe'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from meals.models import Meals
from meals.models import Category
from blog.models import Post
from django.contrib import messages

# Create your views here.
def home(request):
    specials = Meals.objects.filter(category__name='SPECIAL')[:6]
    special1 = specials[0]
    special2 = specials[1]
    special3 = specials[2]
    special4 = specials[3]
    special5 = specials[4]
    special6 = specials[5]
    meal_list = Meals.objects.all()
    categories = Category.objects.all()
    post = Post.objects.last()

    context = {
        'special1':special1,
        'special2': special2,
        'special3': special3,
        'special4': special4,
        'special5': special5,
        'special6': special6,
        'meal_list':meal_list,
        'categories':categories,
        'post':post,

    }


    return render(request,'home/index.html',context)

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


      
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.png' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">

                    <p class="lead">An Asian Fusion Restaurant.</p>
                    <a href="{% url 'subscribe:subscribe' %}"><p class="lead">Subscribe</p></a>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->




        <div class="section" data-aos="fade">
          <div class="container">
            <div class="row justify-content-center text-center" data-aos="fade-up">
              <div class="col-md-8">
                <div class="owl-carousel home-slider-loop-false">


                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita quaerat recusandae molestias incidunt sapiente sit numquam delectus mollitia! Non laudantium impedit voluptas consequatur corrupti. Cumque consequuntur nemo eos et error!&rdquo;</p>
                      <div class="author">

                        <h4>Maxim Smith</h4>

                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Sint adipisci laborum dolorum ipsa quidem alias ipsum aperiam aut! Quis rerum soluta dolorem iure nihil velit error sequi? Dignissimos accusantium adipisci unde officia? Dolores aut sequi dolorum repellendus quod.&rdquo;</p>
                      <div class="author">

                        <h4>Geert Green</h4>

                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Ratione alias iure ab facere quia aliquam dolor et voluptates esse nihil corporis distinctio hic ea quo ducimus autem cum amet. Quos accusamus iusto porro nulla temporibus numquam commodi soluta.&rdquo;</p>
                      <div class="author">

                        <h4>Dennis Roman</h4>

                      </div>
                    </blockquote>
                  </div>
                  <div class="item">
                    <blockquote class="testimonial">
                      <p>&ldquo;Ad quod aspernatur ipsa. Numquam expedita delectus qui ad explicabo voluptas eos vel reiciendis magnam rerum quaerat quisquam accusantium quae saepe ipsam ullam ut ea molestiae porro. Recusandae veniam maxime.&rdquo;</p>
                      <div class="author">

                        <h4>Geert Green</h4>

                      </div>
                    </blockquote>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .section -->
        


         <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                <h2 class="mb-5 text-center">Menu</h2>

                <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                  {% for category in categories %}
                      {% if category.name == 'SPECIAL' %}
                          <li class="nav-item">
                    <a class="nav-link active" id="{{ category }}-tab" data-toggle="pill" href="#{{ category }}" role="tab" aria-controls="{{ category }}" aria-selected="true">{{ category }}</a>
                  </li>
                      {% else %}
                  <li class="nav-item">
                    <a class="nav-link " id="{{ category }}-tab" data-toggle="pill" href="#{{ category }}" role="tab" aria-controls="{{ category }}" aria-selected="false">{{ category }}</a>
                  </li>
                      {% endif %}
                    {% endfor %}
                </ul>
                <div class="tab-content" id="pills-tabContent">
                  {% for category in categories %}
                      {% if category.name == 'SPECIAL' %}
                        <div class="tab-pane fade show active" id="{{ category }}" role="tabpanel" aria-labelledby="{{ category }}-tab">
                      {% else %}
                        <div class="tab-pane fade show " id="{{ category }}" role="tabpanel" aria-labelledby="{{ category }}-tab">
                      {% endif %}

                          {% for meal in meal_list %}
                              {% if category == meal.category %}
                                  <div class="d-block d-md-flex menu-food-item" style="padding-bottom: 0; margin-bottom: 10px;">
                                  <div class="text order-1 mb-3">
                                    <h3><a href="{% url 'meals:meal_detail' slug=meal.slug %}">{{ meal.name }}</a></h3>
                                    <p>{{ meal.description }}</p>
                                  </div>
                                  <div class="price order-2">
                                    <strong>${{ meal.price }}</strong>
                                  </div>
                                </div> <!-- .menu-food-item -->
                              {% endif %}
                          {% endfor %}


                      </div>
                    {% endfor %}
                </div>


              </div>
            </div>
          </div>
        </div>

         <!-- .section test-->
            <div>
  <div class="carousel" style="z-index: 1;">
    <ul class="slides">
      <input type="radio" name="radio-buttons" id="img-1" checked />
      <li class="slide-container">
        <div class="slide-image">
          <img src="https://upload.wikimedia.org/wikipedia/commons/9/9e/Timisoara_-_Regional_Business_Centre.jpg">
        </div>

        <div class="carousel-controls">
          <label for="img-3" class="prev-slide">
            <span>&lsaquo;</span>
          </label>
          <label for="img-2" class="next-slide">
            <span>&rsaquo;</span>
          </label>
            <p class="p_text">title-1</p>
        </div>
      </li>
      <input type="radio" name="radio-buttons" id="img-2" />
      <li class="slide-container">
        <div class="slide-image">
          <img src="https://content.r9cdn.net/rimg/dimg/db/02/06b291e8-city-14912-171317ad83a.jpg?width=1750&height=1000&xhint=3040&yhint=2553&crop=true">
        </div>
        <div class="carousel-controls">
          <label for="img-1" class="prev-slide">
            <span>&lsaquo;</span>
          </label>
          <label for="img-3" class="next-slide">
            <span>&rsaquo;</span>
          </label>
            <p class="p_text">title-2</p>
        </div>
      </li>
      <input type="radio" name="radio-buttons" id="img-3" />
      <li class="slide-container">
        <div class="slide-image">
          <img src="https://speakzeasy.files.wordpress.com/2015/05/twa_blogpic_timisoara-4415.jpg">
        </div>
        <div class="carousel-controls">
          <label for="img-2" class="prev-slide">
            <span>&lsaquo;</span>
          </label>
          <label for="img-1" class="next-slide">
            <span>&rsaquo;</span>
          </label>
            <p class="p_text">title-3</p>
        </div>
      </li>
      <div class="carousel-dots">
        <label for="img-1" class="carousel-dot" id="img-dot-1"></label>
        <label for="img-2" class="carousel-dot" id="img-dot-2"></label>
        <label for="img-3" class="carousel-dot" id="img-dot-3"></label>
      </div>
    </ul>
  </div>
</div>
         <!-- .section test-->






        <div class="section bg-light">
          <div class="container">
            <div class="row justify-content-center mb-5" data-aos="fade-up">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Events &amp; News</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga, alias distinctio voluptatum magni voluptatibus.</p>
              </div>
            </div>
            <div class="row" style="display: flex;justify-content: center;align-items: center;text-align: center;">

                    <div class="col-lg-6">
                    <div class="media d-block d-lg-flex mb-5"  data-aos="fade-up" data-aos-delay="100" style="display:flex;justify-content: center;align-items: center;">
                      <figure class="mr-4 horizontal" style="width: 100%" >
                          <a href="{% url 'blog:post_detail' post.id%}">
                        <img src="{{ post.image.url }}" alt="Image placeholder" class="img-fluid" >
                          </a>
                      </figure>

                    </div> <!-- .media -->
                        <div class="media-body">
                        <h3><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h3>
                        <p class="post-meta"><span><span class="fa fa-calendar"></span> {{ post.created }}</span></p>
                        <p>{{ post.content|truncatechars:80 }}</p>
                        <p><a href="{% url 'blog:post_list' %}" class="btn btn-primary btn-outline-primary btn-sm">More News</a></p>

                      </div>
                  </div> <!-- .col-md-6 -->


            </div>
          </div>
        </div> <!-- .section -->

        <div class="section services-section">
          <div class="container">

            <div class="row">
              <div class="col-md-6 col-lg-3" data-aos="fade-up">
                <div class="media feature-icon d-block text-center">
                  <div class="icon" style="background-color: #ffffff">
                    <img src="{% static 'site_static/img/food.png' %} " alt="Slider Image" width="auto" height="72">
                  </div>
                  <div class="media-body">
                    <h3>Easy Reservation</h3>
                    <p style="opacity: 0;">Our team of chefs is dedicated to providing high-quality cuisine, combining traditional and modern cooking techniques to ensure that every dish will satisfy your taste buds. Our dishes are not only delicious, but also carefully presented, bringing you a double feast for the eyes and taste.</p>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="100">
                <div class="media feature-icon d-block text-center">
                  <div class="icon" style="background-color: #ffffff">
                    <img src="{% static 'site_static/img/shrimp.png' %} " alt="Slider Image" width="auto" height="72">
                  </div>
                  <div class="media-body">
                    <h3>Fresh Food</h3>
                    <p style="opacity: 0;">We insist on using the freshest ingredients, which are purchased directly from local farms every day to ensure the freshness and nutrition of the food. Fresh ingredients not only enhance the taste of the dishes, but also allow you to enjoy a healthier diet.</p>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="300">
                <div class="media feature-icon d-block text-center">
                  <div class="icon" style="background-color: #ffffff">
                    <img src="{% static 'site_static/img/waiter.png' %} " alt="Slider Image" width="auto" height="72">
                  </div>
                  <div class="media-body">
                    <h3>Friendly Staff</h3>
                    <p style="opacity: 0;">Our service team is friendly and professional, providing you with personalized service from the moment you walk in the door, ensuring that every customer has a home experience. Whatever your needs, our staff will do their best to meet them.</p>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="500">
                <div class="media feature-icon d-block text-center">
                  <div class="icon" style="background-color: #ffffff">
                    <img src="{% static 'site_static/img/best-seller.png' %} " alt="Slider Image" width="auto" height="72">
                  </div>
                  <div class="media-body">
                    <h3>Quality Cuisine</h3>
                    <p style="opacity: 0;">Booking a seat is simple and fast. You can easily make an appointment by phone or mobile app. Our system will provide you with real-time table information and reservation confirmation services to ensure that your dining plan goes smoothly.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .section -->
      </div>



    {% endblock %}

<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>Hello</p>
  </div>
</div>

home/templates/home/indextest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ special1 }}
{{ special2 }}
{{ special6 }}

</body>
</html>