blog/urls.py
from django.urls import path
from . import views

app_name ='blog'
urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('<int:id>', views.post_detail,name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag,name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category,name='post_by_category'),
    path('post_new/',views.post_new,name='post_new'),
]

get/urls.py
from django.urls import path
from . import views

app_name ='get'
urlpatterns = [
    path('', views.get_statistic,name='get_statistic'),
    path('login/', views.login_view,name='login_view'),
    path('menu_panel/',views.menu_panel,name='menu_panel'),
    path('post_new_meal/',views.post_new_meal,name='post_new_meal'),
    path('delete_meal/<slug:slug>',views.delete_meal,name='delete_meal'),
    path('modify_meal/<slug:slug>',views.modify_meal,name='modify_meal'),
    path('send_email/',views.send_email,name='send_email'),
    path('blog_panel/',views.blog_panel,name='blog_panel'),
    path('post_new_blog/',views.post_new_blog,name='post_new_blog'),
    path('delete_blog/<int:id>',views.delete_blog,name='delete_blog'),
    path('modify_blog/<int:id>',views.modify_blog,name='modify_blog'),
    path('show_email/',views.show_email,name='show_email'),
]

newtropical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
    path('subscribe/',include('subscribe.urls',namespace='subscribe')),
    path('about-us/',include('aboutus.urls',namespace='aboutus')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('',include('home.urls',namespace='home')),
    path('get/',include('get.urls',namespace='get')),
]
+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT))

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/',blank=True,null=True)
    tags = TaggableManager(blank=True,related_name='Posts')
    category=models.ForeignKey('Category',null=True,on_delete=models.CASCADE,related_name='posts')

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title

class Category(models.Model):
    category_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name

blog/forms.py
from django import forms
from .models import Post

class PostTableForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'tags',
        ]

blog/views.py
from django.shortcuts import render
from .models import *
from taggit.models import Tag
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import PostTableForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import smtplib
import os
from dotenv import load_dotenv


# Create your views here.
def post_list(request):
    post_list = Post.objects.all().order_by('-id')

    ##search
    search_query = request.GET.get('q')
    if search_query:
        post_list = post_list.filter(
            Q(title__icontains=search_query)|
            Q(content__icontains=search_query)|
            Q(tags__name__icontains=search_query)
        ).distinct()
    paginator = Paginator(post_list, 5)  # Show 25 contacts per page.

    page_number = request.GET.get("page")
    post_list = paginator.get_page(page_number)
    context = {
        'post_list':post_list
    }
    return render(request,'Post/post_list.html',context)
def post_detail(request,id):
    post_detail = Post.objects.get(id=id)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    context = {
        'post_detail':post_detail,
        'categories':categories,
        'tags':tags
    }
    return render(request,'Post/post_detail.html',context)

def post_by_tag(request,tag):
    post_by_tag = Post.objects.filter(tags__name__in=[tag])
    context = {
        'post_list':post_by_tag,
    }
    return render(request, 'Post/post_list.html', context)

def post_by_category(request,category):
    post_by_category = Post.objects.filter(category__category_name=category)
    context = {
        'post_list': post_by_category,
    }
    return render(request, 'Post/post_list.html', context)

@login_required(login_url='get:login_view')
def post_new(request):
    form = PostTableForm
    message = ''
    context = {
        'form':form,
    }
    if request.method == 'POST':
        form = PostTableForm(request.POST,request.FILES)
        author = request.user
        title = request.POST.get('title')
        content = request.POST.get('content')
        tags = request.POST.get('tags')
        image = request.FILES.get('image')
        category = request.POST.get('category')
        try:
            get_category = Category.objects.get(category_name=category)
        except Category.DoesNotExist:
            Category.objects.create(category_name=category)
            get_category = Category.objects.get(category_name=category)

        get_author = User.objects.get()
        post = Post.objects.create(
            author=author,
            title=title,
            content=content,
            image=image,
            category=get_category
        )
        tag_list = [tag.strip() for tag in tags.split(',')]

        for tag_name in tag_list:
            try:
                get = Tag.objects.get(name=tag_name)
            except Tag.DoesNotExist:
                Tag.objects.create(name=tag_name)
                get = Tag.objects.get(name=tag_name)
            post.tags.add(get)
        post.save()


        return render(request,'Post/post_new.html',context={'form':form,'message':'Post successfully'})

    return render(request,'Post/post_new.html',context)

blog/templates/Post/post_detail.html
{% extends 'base.html' %}
{% load static %}
      {% block body %}
      
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7 text-center" data-aos="fade-up">
                  <h2 class="heading mb-4">{{ post_detail.title }}</h2>

                  <div class="post-info">
                    <div class="date-info">{{ post_detail.created }}</div>
                    <div class="category-info"><span class="seperator">|</span>In <a href="#" data-title="View all posts in Lifestyle" title="View all posts in Lifestyle">{{ post_detail.category }}</a></div>
                    <div class="author-info"><span class="seperator">|</span>By <a href="#">Pius</a></div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">
            
            <div class="row">

              <div class="col-md-8">
                <p> {{ post_detail.content }}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                  <div class="tagcloud">
                    {% for tag in post_detail.tags.all %}
                    <a href="{% url 'blog:post_by_tag' tag  %}" class="tag-cloud-link">{{ tag.name }}</a>
                    {% endfor %}
                  </div>
                </div>




              </div> <!-- .col-md-8 -->
              <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                  <form action="{% url 'blog:post_list' %}" method="GET" class="search-form">
                    <div class="form-group">
                      <span class="icon fa fa-search"></span>
                      <input type="text" class="form-control" name='q' value="{{ request.GET.q }}" placeholder="Type a keyword and hit enter">
                    </div>
                  </form>
                </div>
                <div class="sidebar-box">
                  <div class="categories">
                    <h3>Categories</h3>
                    {% for category in categories %}
                        <li><a href="{% url 'blog:post_by_category' category.id %}">{{ category }} <span>({{ category.posts.count }})</span></a></li>
                    {% endfor %}
                  </div>
                </div>
                <div class="sidebar-box">
                  <img src="img/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
                  <h3>About The Author</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
                  <p><a href="#" class="btn btn-primary btn-sm">Read More</a></p>
                </div>

                <div class="sidebar-box">
                  <h3>Tag Cloud</h3>
                  <div class="tagcloud">
                      {% for tag in tags %}
                        <a href="{% url 'blog:post_by_category' tag.name %}" class="tag-cloud-link">{{ tag }}</a>
                      {% endfor %}

                  </div>
                </div>

                <div class="sidebar-box">
                  <h3>Paragraph</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
                </div>
              </div>

            </div>

            
          </div>
        </div> <!-- .section -->
      


      </div> <!-- .main-wrap -->
      

      {% endblock %}

blog/templates/Post/post_list.html
{% extends 'base.html' %}
{% load static %}
      {% block body %}
      
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Evnet & News</h2>

                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">
            
            <div class="row mb-5">
                {% for post in post_list %}

                  <div class="col-md-8">
                    <div class="media d-block media-bg-white mb-5" data-aos="fade-up"  data-aos-delay="400" style="width: 1200px;max-height: 500px;">
                      <figure style="display: flex;justify-content: center;">
                        <a href="{% url 'blog:post_detail' post.id %}"><img src="{{ post.image.url }}" alt="Image placeholder" class="img-fluid" style="max-height: 300px;overflow: hidden;"></a>
                          <div class="media-body">
                        <h3><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h3>
                        <p class="post-meta"><span><span class="fa fa-calendar"></span> {{ post.created }}</span></p>
                        <p class="mb-4">{{ post.content|truncatechars:20 }}</p>
                        <p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>

                    </div> <!-- .media -->
                      </figure>

                  </div>
                    </div>
                {% endfor %}


            </div>

            <div class="row">
              <div class="col-md-12">
                    <span class="step-links">
        {% if post_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ post_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
        </span>

        {% if post_list.has_next %}
            <a href="?page={{ post_list.next_page_number }}">next</a>
            <a href="?page={{ post_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>



              </div>
            </div>
          </div>
        </div> <!-- .section -->
      


      </div> <!-- .main-wrap -->
      

      {% endblock %}

blog/templates/Post/post_new.html
{% extends 'base.html' %}
{% load static %}
      {% block body %}
      
      <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'site_static/img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Post New Blog</h2>
                  <p class="lead">Post your news!/p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">

            <div class="row mb-5">
                {% if message %}
                    {{ message }}
                {% endif %}
                <br>
                <br>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <input type="file" name="image" accept="image/*">
                    <label for="categories">Category:</label>
                    <input type="text" class="category" name="category">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>


            </div>

            <div class="row">
              <div class="col-md-12">
                    <span class="step-links">
    </span>



              </div>
            </div>
          </div>
        </div> <!-- .section -->
      


      </div> <!-- .main-wrap -->
      

      {% endblock %}