aboutus/urls.py
from django.urls import path
from . import views

app_name ='aboutus'
urlpatterns = [
    path('', views.aboutus_list,name='aboutus_list'),
]

blog/urls.py
from django.urls import path
from . import views

app_name ='blog'
urlpatterns = [
    path('', views.post_list,name='post_list'),
    path('<int:id>', views.post_detail,name='post_detail'),
    path('tags=<slug:tag>', views.post_by_tag,name='post_by_tag'),
    path('category=<slug:category>', views.post_by_category,name='post_by_category'),
    path('post_new/',views.post_new,name='post_new'),
]

get/urls.py
from django.urls import path
from . import views

app_name ='get'
urlpatterns = [
    path('', views.get_statistic,name='get_statistic'),
    path('login/', views.login_view,name='login_view'),
    path('menu_panel/',views.menu_panel,name='menu_panel'),
    path('post_new_meal/',views.post_new_meal,name='post_new_meal'),
    path('delete_meal/<slug:slug>',views.delete_meal,name='delete_meal'),
    path('modify_meal/<slug:slug>',views.modify_meal,name='modify_meal'),
    path('send_email/',views.send_email,name='send_email'),
    path('blog_panel/',views.blog_panel,name='blog_panel'),
    path('post_new_blog/',views.post_new_blog,name='post_new_blog'),
    path('delete_blog/<int:id>',views.delete_blog,name='delete_blog'),
    path('modify_blog/<int:id>',views.modify_blog,name='modify_blog'),
    path('show_email/',views.show_email,name='show_email'),
]

meals/urls.py
from django.urls import path
from . import views

app_name ='meals'
urlpatterns = [
    path('', views.meal_list,name='meal_list'),
    path('<slug:slug>',views.meal_detail,name='meal_detail')
]

newtropical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
    path('subscribe/',include('subscribe.urls',namespace='subscribe')),
    path('about-us/',include('aboutus.urls',namespace='aboutus')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('',include('home.urls',namespace='home')),
    path('get/',include('get.urls',namespace='get')),
]
+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT))

subscribe/urls.py
from django.urls import path
from . import views

app_name ='subscribe'
urlpatterns = [
    path('sub/', views.subscribefunction,name='subscribe'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>The Tropical Island Restaurant</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'site_static/fonts/fontawesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'site_static/fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'site_static/css/style.css' %}">
  </head>
  <body>


    <div class="site-wrap">

      <nav class="site-menu">
        <div class="site-menu-inner">
          <ul class="list-unstyled">
            <li class="active" style="z-index: 3;"><a href="/">Home</a></li>
            <li><a href="{% url 'aboutus:aboutus_list' %}">About Us</a></li>
            <li><a href="{% url 'meals:meal_list' %}">Menu</a></li>
            <li><a href="{% url 'blog:post_list' %}">Event & News</a></li>
            <li><a href="{% url 'subscribe:subscribe' %}">Subscribe Us</a></li>
          </ul>
        </div>
      </nav>

      <header class="site-header">
        <div class="row align-items-center">
          <div class="col-5 col-md-3">
             <ul class="list-unstyled social">
              <li><a href="#"><span class="fa fa-facebook"></span></a></li>

              <li><a href="#"><span class="fa fa-instagram"></span></a></li>
            </ul>
          </div>
          <div class="col-2 col-md-6 text-center">
            <a href="/" class="site-logo" style="border: 2px solid transparent"><img src="{% static 'site_static/img/logo.png' %} " height="100" width="auto"></a>
          </div>
          <div class="col-5 col-md-3 text-right menu-burger-wrap">
            <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>

          </div>
        </div>

      </header> <!-- site-header -->
      
      {% block body %}

      {% endblock %}

      <footer>
        <div class="site-footer">
          <div class="container">
            <div class="row small-gutters mb-5">
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3>About Restaurant</h3>
                  <p>We are an Asian fusion restaurant. We will provide you with meticulous service and food</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                <div class="footer-widget">
                  <h3>Lunch Service</h3>
                  <p>Wed to Sun: <br>11:30 am - 2:30 pm</p>
                  <h3>Dinner Service</h3>
                  <p>Wed to Sun: <br>5:00 pm - 8:30 pm</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="300">
                <div class="footer-widget footer-contact-widget">
                  <h3>Contact Us</h3>
                  <p class="contact-email">info@yourdomain.com</p>
                    <h3>Location</h3>
                    <a href="https://www.google.ca/maps/place/The+Tropical+Island+Restaurant/@48.4600223,-123.3358682,17z/data=!3m1!4b1!4m6!3m5!1s0x548f73ef7fc65edd:0xb352e100702560f8!8m2!3d48.4600188!4d-123.3332933!16s%2Fg%2F1vm_xkyq?entry=ttu"><p class="ion-ios-location"> 3690 Shelbourne St #1, Victoria</p></a>
                    <h3>Phone</h3>
                  <p class="contact-phone" style="font-size: large;">(250) 477-2538</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="400">
                <div class="footer-widget footer-contact-widget">

                  <h3>Subscribe</h3>
                  <a href="{% url 'subscribe:subscribe' %}">Click Here</a>

                  
                  
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </footer>

      <div class="site-footer-copyright">
        <div class="container">
          <div class="row">

             <p class="footer-text col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This website is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://github.com/Tony031201" target="_blank">Tony</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>

    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'site_static/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'site_static/js/popper.min.js' %}"></script>
    <script src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site_static/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'site_static/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'site_static/js/jquery.stellar.min.js' %}"></script>

    <script src="{% static 'site_static/js/aos.js' %}"></script>
    

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="{% static 'site_static/js/main.js' %}"></script>
  </body>
</html>